/*
 * This source file was generated by the Gradle 'init' task
 */
package smolrx;

import java.io.IOException;

public class App {

    public static void main(String[] args) {
        System.out.println(args[0]);
        if (args[0].equals("server")) {
            try {
                Server s = new Server(6444, 5);
                s.start();
            } catch (IOException e) {
                e.printStackTrace();
            }
        } else {
            Client c = new Client("localhost", 6444);
            c.run();
        }
    }
}
